# Generated by Django 4.0.4 on 2022-05-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='counting',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
