# Generated by Django 4.0.4 on 2022-05-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment_author_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
